execute if entity @s[hasitem={item=minecraft:kelp}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:dried_kelp
execute if entity @s[hasitem={item=minecraft:potato}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:baked_potato
execute if entity @s[hasitem={item=minecraft:beef}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:cooked_beef
execute if entity @s[hasitem={item=minecraft:rotten_flesh}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:leather
execute if entity @s[hasitem={item=minecraft:porkchop}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:cooked_porkchop
execute if entity @s[hasitem={item=minecraft:rabbit}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:cooked_rabbit
execute if entity @s[hasitem={item=minecraft:cod}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:cooked_cod
execute if entity @s[hasitem={item=minecraft:salmon}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:cooked_salmon
execute if entity @s[hasitem={item=minecraft:mutton}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:cooked_mutton
execute if entity @s[hasitem={item=minecraft:melon_slice}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:glistering_melon_slice
execute if entity @s[hasitem={item=minecraft:chicken}] run replaceitem entity @s slot.weapon.mainhand 0 minecraft:cooked_chicken